version: "3.8"
services:
  app:
    build: .
    container_name: discord-example-app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "4040:4040"
    command: [npm run dev, ngrok http 3000]
    # command: npm run dev
    environment:
      - NODE_ENV=development
